-- config_ui/persist.lua -- load/save/reset config
local ConfigUI = require("src.config_ui.detect")

local DEFAULT_CONFIG = {
  brokerId = "", modemAddress = "", telemetryPort = 123, controlPort = 124,
  useStateMachine = false, useProgramFramework = false, useTimeSliceScheduler = false,
  useCoroutineTransfer = false, enableAutoCrafting = false, autoCraftInputs = {},
  enableDiscovery = false, minMachines = 1, enablePersistence = false,
  enableRemoteControl = false, enableRemoteThrottle = false, enableRemoteRestart = false,
  controlAuthSecret = "", machines = {}, machineTypes = {},
  redstoneAddress = "", redstoneSide = 5,
  meControllerAddr = "", databaseAddr = "", machineTransposers = {},
  pollInterval = 0.5, heartbeatInterval = 2.0, debounceWindow = 1.5,
  queueSize = 64, dbSlots = 9,
}

-- ===========================================================================
-- Config persistence
-- ===========================================================================

--- Load config from the filesystem.
-- @return table or nil  config, or nil if file doesn't exist/corrupt
function ConfigUI:loadConfig()
  -- Try multiple ways to get the filesystem component
  local fs = self._filesystem
  if not fs then
    local ok, mod = pcall(require, "filesystem")
    if ok and mod then fs = mod
    else
      local okc = pcall(require, "component")
      if okc then fs = require("component").filesystem end
    end
  end
  if not fs or type(fs.exists) ~= "function" then
    return nil, "Filesystem library not available"
  end

  local path = self._configPath
  local exists
  local existsOk, existsVal = pcall(fs.exists, path)
  if existsOk then
    exists = existsVal
  else
    exists = false
  end

  if not exists then
    return nil, "Config file not found: " .. tostring(path)
  end

  local ok, fh = pcall(io.open, path, "r")
  if not ok or not fh then
    return nil, "Could not open config file for reading"
  end

  local content = fh:read("*a")
  fh:close()

  if not content or #content == 0 then
    return nil, "Config file is empty"
  end

  -- Try to load as serialized Lua table
  local loadOk, chunk = pcall(load, content)
  if not loadOk then
    return nil, "Config file contains invalid Lua syntax: " .. tostring(chunk)
  end

  local execOk, config = pcall(chunk)
  if not execOk or type(config) ~= "table" then
    return nil, "Config file contains invalid Lua data"
  end

  -- Validate basic structure
  if type(config.version) ~= "string" then
    config.version = ConfigUI.VERSION
  end

  self._config = config
  return config, nil
end


-- ===========================================================================
-- Safe date helper (os.date returns a table in OC, a string in standard Lua)
-- ===========================================================================
local function _safeDate()
  local d = os.date()
  if type(d) == "table" then
    -- OC returns a broken-down time table; format it manually
    return string.format("%04d-%02d-%02d %02d:%02d:%02d",
      d.year or 0, d.month or 0, d.day or 0,
      d.hour or 0, d.min  or 0, d.sec  or 0)
  end
  return tostring(d)
end
--- Save config to the filesystem.
-- @param config  table  configuration to persist
-- @return boolean, string  success, error message
function ConfigUI:saveConfig(config)
  config = config or self._config
  if not config then
    return false, "No config to save"
  end

  -- Add version marker
  config.version = ConfigUI.VERSION
  config._savedAt = os.time()

  -- Serialize to Lua table format
  local ok, serialized = pcall(self._serializeTable, self, config, "")
  if not ok then
    return false, "Serialization failed: " .. tostring(serialized)
  end
  if type(serialized) ~= "string" then
    return false, "Serialization returned a non-string: " .. type(serialized)
  end

  local path = tostring(self._configPath)   -- guard: must be a string for io.open
  local fh, openErr = io.open(path, "w")
  if not fh then
    return false, "Could not open config file for writing (" .. path .. "): " .. tostring(openErr)
  end

  -- os.date() returns a table in OC — use _safeDate() instead of os.date()
  local header = table.concat({
    "return {\n",
    "  -- AE2-ES Exec Broker Config\n",
    "  -- Generated by config_ui.lua v", tostring(ConfigUI.VERSION), "\n",
    "  -- Saved: ", _safeDate(), "\n\n",
  })

  -- Remove outer braces from serialized table since we already wrote "return {"
  local body = serialized
  if body:sub(1, 1) == "{" then
    body = body:sub(2, #body - 1)
    body = body:gsub("^\n", "")
  end

  -- Write strings explicitly — OC io/buffer rejects non-string arguments
  fh:write(tostring(header))
  fh:write(tostring(body))
  fh:write("\n}\n")
  fh:close()

  self._config = config
  print("Config saved to " .. path)
  return true, nil
end
--- Recursively serialize a Lua table to a compact Lua string.
-- @param t     table
-- @param indent  string  current indentation
-- @param top     boolean  top-level call
-- @return string
function ConfigUI:_serializeTable(t, indent, top)
  indent = indent or ""
  if type(t) ~= "table" then
    return self:_serializeValue(t)
  end

  -- Empty table
  if next(t) == nil then
    return "{}"
  end

  -- Check if array-like
  local isArray = true
  local maxIdx = 0
  for k, _ in pairs(t) do
    if type(k) ~= "number" or k <= 0 or math.floor(k) ~= k then
      isArray = false
    end
    if type(k) == "number" and k > maxIdx then
      maxIdx = k
    end
  end

  local parts = {}
  local count = 0

  if isArray then
    -- Array-style serialization
    table.insert(parts, "{\n")
    for i = 1, maxIdx do
      if t[i] ~= nil then
        local val = self:_serializeValue(t[i])
        table.insert(parts, indent .. "  " .. val .. ",\n")
        count = count + 1
      end
    end
    table.insert(parts, indent .. "}")
  else
    -- Map-style serialization
    local keys = {}
    for k, _ in pairs(t) do
      table.insert(keys, k)
    end
    table.sort(keys, function(a, b) return tostring(a) < tostring(b) end)

    table.insert(parts, "{\n")
    for _, k in ipairs(keys) do
      local val = t[k]
      local keyStr
      if type(k) == "string" then
        local reserved = {
          ["and"]=true,["break"]=true,["do"]=true,["else"]=true,
          ["elseif"]=true,["end"]=true,["false"]=true,["for"]=true,
          ["function"]=true,["if"]=true,["in"]=true,["local"]=true,
          ["nil"]=true,["not"]=true,["or"]=true,["repeat"]=true,
          ["return"]=true,["then"]=true,["true"]=true,["until"]=true,
          ["while"]=true,
        }
        if k:match("^[%a_][%w_]*$") and not reserved[k] then
          keyStr = k
        else
          keyStr = "[\"" .. k:gsub("\"", "\\\"") .. "\"]"
        end
      else
        keyStr = "[" .. tostring(k) .. "]"
      end

      if type(val) == "table" then
        local child = self:_serializeTable(val, indent .. "  ")
        table.insert(parts, indent .. "  " .. keyStr .. " = " .. child .. ",\n")
      else
        local valStr = self:_serializeValue(val)
        table.insert(parts, indent .. "  " .. keyStr .. " = " .. valStr .. ",\n")
      end
    end
    table.insert(parts, indent .. "}")
  end

  return table.concat(parts)
end

--- Serialize a single value to Lua literal form.
function ConfigUI:_serializeValue(val)
  local t = type(val)
  if t == "nil" then return "nil" end
  if t == "boolean" then return tostring(val) end
  if t == "number" then
    if val == math.floor(val) and val < 9007199254740992 then
      return tostring(math.floor(val))
    end
    return string.format("%g", val)
  end
  if t == "string" then
    -- Escape control characters and backslashes
    local escaped = val:gsub("\\", "\\\\"):gsub("\"", "\\\""):gsub("\n", "\\n"):gsub("\r", "\\r"):gsub("\t", "\\t")
    return "\"" .. escaped .. "\""
  end
  -- Tables: recursively serialize; functions/userdata: placeholder
  if t == "table" then return self:_serializeTable(val, "")
  elseif t == "function" then return "\"<function>\""
  elseif t == "userdata" then return "\"<userdata>\""
  else return "\"<" .. t .. ">\""
  end
end

--- Reset config to factory defaults.
-- @return table  fresh default config
function ConfigUI:resetConfig()
  local config = {}
  for k, v in pairs(DEFAULT_CONFIG) do
    if type(v) == "table" then
      config[k] = {}
      for k2, v2 in pairs(v) do
        config[k] = { k2, v2 }
        config[k] = nil
      end
      config[k] = {}
    else
      config[k] = v
    end
  end
  self._config = config
  return config
end


return ConfigUI
